name: '${plugin_name}'
version: '${plugin_version}'
main: ${plugin_group}.PaperCutter
api-version: '1.13'
load: STARTUP
authors: [ ${ plugin_authors } ]
description: ${plugin_description}
commands:
  PaperCutter:
    description: "Manager Command"
    aliases: "pc"
permissions:
  ${plugin_group}.reload:
    description: "/dt reload"
    default: op