name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    concurrency:
      group: nightly
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew clean shadowJar

      - name: Create GitHub Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_REPLACE: true
          GHR_PATH: build/libs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
