name: publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    concurrency:
      group: publish
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # AdoptOpenJDK
          java-version: '17'

      - name: publish
        env:
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew clean publish

      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'nightly'
          name: 'Nightly $$-${{ github.run_id }}'
          prerelease: false
          body: 'nightly version'
          files: |
            ./build/libs/*
